# Generated by Django 5.2.9 on 2025-12-03 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_problema_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INTERESSADA', 'Interessada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='INTERESSADA', max_length=20)),
                ('mensagem', models.TextField(blank=True, help_text='Mensagem da oficina sobre o serviço', null=True)),
                ('data_interesse', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_manifesto', to=settings.AUTH_USER_MODEL)),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='core.problema')),
            ],
            options={
                'ordering': ['-data_interesse'],
                'unique_together': {('problema', 'oficina')},
            },
        ),
    ]
