# Generated by Django 5.2.9 on 2025-12-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Foto do problema', null=True, upload_to='problemas/'),
        ),
    ]
